"""Universal Multi-Provider LLM Router with Native Ollama Streaming, Direct Gemini API, Keep-Alive, & Fast Fallbacks.

Supports:
- Google Gemini direct API with multi-model fallback (`gemini-flash-latest`, `gemini-2.0-flash`, `gemini-1.5-flash`)
- Real-time token-by-token streaming from Local Ollama (`llama3.2:latest`, `qwen2.5:3b`)
- OpenAI (`gpt-4o`, `gpt-4o-mini`), Anthropic Claude, Groq, OpenRouter via LiteLLM
- Background persistent keep-alive in RAM
- Deterministic Math Grounding fallback
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import urllib.error
import urllib.request
from typing import AsyncGenerator, Any

from rich.console import Console

from engine.config import FinanceConfig

console = Console(stderr=True)
logger = logging.getLogger("finance_controller.router")

GEMINI_FALLBACK_MODELS = [
    "gemini-flash-lite-latest",
    "gemini-3.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-3.6-flash",
    "gemini-flash-latest",
]


def _extract_gemini_text(res_data: dict[str, Any]) -> str:
    """Safely extracts combined text from Gemini response parts (handling reasoning/thinking models)."""
    candidates = res_data.get("candidates", [])
    if not candidates:
        return ""
    cand = candidates[0]
    parts = cand.get("content", {}).get("parts", [])
    texts = [p.get("text", "") for p in parts if "text" in p]
    return " ".join([t.strip() for t in texts if t.strip()]).strip()


class UniversalLLMRouter:
    def __init__(self):
        self.ollama_base_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

    def warmup_ollama(self, model_name: str = "llama3.2:latest") -> None:
        """Pre-warms Ollama model in background so it stays pinned in RAM with zero cold-start delay."""
        try:
            url = f"{self.ollama_base_url}/api/chat"
            payload = {
                "model": model_name.replace("ollama/", "").strip(),
                "messages": [{"role": "user", "content": "ping"}],
                "stream": False,
                "keep_alive": "2h",
                "options": {"num_ctx": 2048, "num_predict": 1},
            }
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                pass
            console.print(f"[bold green][+] [LLM Router][/bold green] Local Ollama model [bold]{model_name}[/bold] warmed up and pinned in RAM.")
        except Exception as e:
            console.print(f"[dim][*] [LLM Router] Ollama warmup note: {e}[/dim]")

    def _resolve_model_id(self, provider: str | None, model: str | None) -> tuple[str, str, str]:
        cfg = FinanceConfig.load()
        prov = (provider or cfg.get("llm_provider", "gemini")).lower()
        mod = model or cfg.get("llm_model", "gemini-flash-latest")
        api_key = cfg.get("api_key") or os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY") or ""

        if "gemini-2.5-flash" in mod:
            mod = "gemini-flash-latest"

        if prov == "ollama":
            if not mod.startswith("ollama/"):
                mod = f"ollama/{mod}"
            if mod == "ollama/llama3.2":
                mod = "ollama/llama3.2:latest"
            return "ollama", mod, ""
        elif prov == "gemini":
            clean_mod = mod.replace("gemini/", "").strip()
            if not clean_mod or clean_mod in ("default", "gemini-2.5-flash"):
                clean_mod = "gemini-flash-latest"
            return "gemini", clean_mod, api_key
        elif prov == "openai" and not mod.startswith("openai/"):
            return "openai", mod, api_key
        elif prov == "anthropic" and not mod.startswith("anthropic/"):
            return "anthropic", f"anthropic/{mod}", api_key
        elif prov == "groq" and not mod.startswith("groq/"):
            return "groq", f"groq/{mod}", api_key
        elif prov == "openrouter" and not mod.startswith("openrouter/"):
            return "openrouter", f"openrouter/{mod}", api_key

        return prov, mod, api_key

    async def stream_response(
        self,
        system_prompt: str,
        user_prompt: str,
        provider: str | None = None,
        model: str | None = None,
        max_tokens: int = 2048,
        temperature: float = 0.1,
    ) -> AsyncGenerator[str, None]:
        """Streams tokens in real-time as they are generated by the model."""
        resolved_provider, resolved_model, api_key = self._resolve_model_id(provider, model)

        # ---------------------------------------------------------------------
        # 1. LOCAL OLLAMA STREAMING FAST-PATH
        # ---------------------------------------------------------------------
        if resolved_provider == "ollama" or resolved_model.startswith("ollama/"):
            clean_model = resolved_model.replace("ollama/", "").strip()
            if clean_model in ("llama3.2", "llama3.2:latest"):
                clean_model = "llama3.2:latest"
            elif clean_model in ("qwen2.5", "qwen2.5:3b"):
                clean_model = "qwen2.5:3b"

            url = f"{self.ollama_base_url}/api/chat"
            payload = {
                "model": clean_model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "stream": True,
                "keep_alive": "2h",
                "options": {
                    "num_ctx": 2048,
                    "num_predict": max_tokens,
                    "temperature": temperature,
                },
            }

            console.print(f"[bold cyan]⚡ [LLM Router Stream][/bold cyan] Connecting to local Ollama [bold white]{clean_model}[/bold white] at {self.ollama_base_url}...")
            t0 = time.perf_counter()
            token_count = 0

            try:
                import httpx
                async with httpx.AsyncClient(timeout=45.0) as client:
                    async with client.stream("POST", url, json=payload) as resp:
                        if resp.status_code != 200:
                            console.print(f"[bold red]❌ [Ollama Error][/bold red] HTTP {resp.status_code}")
                            return
                        async for line in resp.aiter_lines():
                            if not line:
                                continue
                            try:
                                chunk = json.loads(line)
                                token = chunk.get("message", {}).get("content", "")
                                if token:
                                    token_count += 1
                                    yield token
                                if chunk.get("done", False):
                                    break
                            except Exception:
                                pass
                elapsed = time.perf_counter() - t0
                tok_sec = round(token_count / elapsed, 1) if elapsed > 0 else 0
                console.print(f"[bold green]✓ [LLM Ollama Stream Complete][/bold green] Generated {token_count} tokens in {elapsed:.2f}s ({tok_sec} tok/s)")
                return
            except Exception as e:
                console.print(f"[yellow]⚠️  [LLM Router][/yellow] Ollama streaming interrupted ({e}). Switching to math grounding.")

        # ---------------------------------------------------------------------
        # 2. GOOGLE GEMINI DIRECT API (Support gemini-flash-latest with auto-fallbacks)
        # ---------------------------------------------------------------------
        if api_key and (resolved_provider == "gemini" or "gemini" in resolved_model):
            clean_model = resolved_model.replace("gemini/", "").strip()
            models_to_try = [clean_model] + [m for m in GEMINI_FALLBACK_MODELS if m != clean_model]

            full_prompt = f"{system_prompt}\n\nUser Question: {user_prompt}" if system_prompt else user_prompt
            payload = {
                "contents": [
                    {
                        "parts": [
                            {"text": full_prompt}
                        ]
                    }
                ],
                "generationConfig": {
                    "maxOutputTokens": max(max_tokens, 2048),
                    "temperature": temperature,
                }
            }
            headers = {
                "Content-Type": "application/json",
                "X-goog-api-key": api_key,
            }

            import httpx
            for try_model in models_to_try:
                console.print(f"[bold magenta]⚡ [Gemini Direct API][/bold magenta] Model: [bold white]{try_model}[/bold white]...")
                t0 = time.perf_counter()
                try:
                    url = f"https://generativelanguage.googleapis.com/v1beta/models/{try_model}:generateContent"
                    async with httpx.AsyncClient(timeout=25.0) as client:
                        resp = await client.post(url, json=payload, headers=headers)
                        if resp.status_code == 200:
                            res_data = resp.json()
                            text = _extract_gemini_text(res_data)
                            if not text:
                                continue
                            elapsed = time.perf_counter() - t0
                            console.print(f"[bold green]✓ [Gemini Response Received][/bold green] from {try_model} in {elapsed:.2f}s")
                            # Yield in natural word chunks for smooth real-time SSE rendering
                            words = text.split(" ")
                            for i, w in enumerate(words):
                                yield w + (" " if i < len(words) - 1 else "")
                                await asyncio.sleep(0.012)
                            return
                        elif resp.status_code in (404, 503, 429):
                            console.print(f"[yellow]⚠️  [Gemini {try_model} returned {resp.status_code}][/yellow] Trying next model...")
                            continue
                        else:
                            console.print(f"[bold red]❌ [Gemini API Error][/bold red] HTTP {resp.status_code}: {resp.text}")
                except Exception as e:
                    console.print(f"[bold red]❌ [Gemini Error on {try_model}][/bold red] {e}")
                    continue

        # ---------------------------------------------------------------------
        # 3. CLOUD PROVIDERS VIA LITELLM (OpenAI, Anthropic, Groq)
        # ---------------------------------------------------------------------
        if api_key and resolved_provider in ("openai", "anthropic", "groq", "openrouter"):
            console.print(f"[bold magenta]⚡ [LLM Cloud Stream][/bold magenta] Connecting to {resolved_provider.upper()} model: [bold white]{resolved_model}[/bold white]...")
            t0 = time.perf_counter()
            token_count = 0
            try:
                import litellm
                litellm.suppress_debug_info = True

                kwargs = {
                    "model": resolved_model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    "max_tokens": max_tokens,
                    "temperature": temperature,
                    "stream": True,
                    "api_key": api_key,
                }
                response = await litellm.acompletion(**kwargs)
                async for chunk in response:
                    delta = chunk.choices[0].delta.content or ""
                    if delta:
                        token_count += 1
                        yield delta
                elapsed = time.perf_counter() - t0
                console.print(f"[bold green]✓ [LLM Cloud Stream Complete][/bold green] Generated {token_count} tokens in {elapsed:.2f}s")
                return
            except Exception as e:
                console.print(f"[bold red]❌ [LLM Cloud Error][/bold red] Stream failed: {e}")

    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        provider: str | None = None,
        model: str | None = None,
        max_tokens: int = 2048,
        temperature: float = 0.1,
    ) -> tuple[str, str, int]:
        """Non-streaming query helper for background tasks."""
        collected = []
        async for token in self.stream_response(
            system_prompt, user_prompt, provider, model, max_tokens, temperature
        ):
            collected.append(token)
        text = "".join(collected)
        if text:
            return text, model or "gemini-flash-latest", len(text.split()) * 2
        return "", "deterministic_math_grounding", 0

    async def test_connection(
        self,
        provider: str | None = None,
        model: str | None = None,
        api_key: str | None = None,
    ) -> dict[str, Any]:
        """Tests live connectivity and measures round-trip latency to the specified LLM endpoint."""
        t0 = time.perf_counter()
        prov, mod, key = self._resolve_model_id(provider, model)
        if api_key:
            key = api_key

        if prov == "ollama" or mod.startswith("ollama/"):
            clean_model = mod.replace("ollama/", "").strip()
            url = f"{self.ollama_base_url}/api/chat"
            payload = {
                "model": clean_model,
                "messages": [{"role": "user", "content": "Respond with READY"}],
                "stream": False,
                "options": {"num_predict": 10},
            }
            try:
                import httpx
                async with httpx.AsyncClient(timeout=10.0) as client:
                    resp = await client.post(url, json=payload)
                    latency = round((time.perf_counter() - t0) * 1000, 2)
                    if resp.status_code == 200:
                        data = resp.json()
                        reply = data.get("message", {}).get("content", "").strip()
                        return {
                            "status": "connected",
                            "provider": "ollama",
                            "model_id": mod,
                            "latency_ms": latency,
                            "reply": reply or "READY",
                            "detail": f"Local Ollama model '{clean_model}' is active & responding at {self.ollama_base_url}.",
                        }
                    else:
                        return {
                            "status": "error",
                            "provider": "ollama",
                            "model_id": mod,
                            "latency_ms": latency,
                            "reply": "",
                            "detail": f"Ollama HTTP {resp.status_code}: {resp.text}",
                        }
            except Exception as e:
                latency = round((time.perf_counter() - t0) * 1000, 2)
                return {
                    "status": "error",
                    "provider": "ollama",
                    "model_id": mod,
                    "latency_ms": latency,
                    "reply": "",
                    "detail": f"Cannot connect to local Ollama daemon ({e}). Ensure Ollama is running (`ollama serve`).",
                }

        # Gemini Direct API Test (with exact curl payload)
        if prov == "gemini" or "gemini" in mod:
            if not key:
                return {
                    "status": "error",
                    "provider": "gemini",
                    "model_id": mod,
                    "latency_ms": 0,
                    "reply": "",
                    "detail": "Gemini API key is required. Please enter your API key to test.",
                }
            try:
                clean_mod = mod.replace("gemini/", "").strip()
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{clean_mod}:generateContent"
                payload = {
                    "contents": [{"parts": [{"text": "Respond with READY"}]}],
                    "generationConfig": {"maxOutputTokens": 200}
                }
                import httpx
                async with httpx.AsyncClient(timeout=25.0) as client:
                    resp = await client.post(url, json=payload, headers={"Content-Type": "application/json", "X-goog-api-key": key})
                    latency = round((time.perf_counter() - t0) * 1000, 2)
                    if resp.status_code == 200:
                        data = resp.json()
                        reply = _extract_gemini_text(data) or "READY"
                        return {
                            "status": "connected",
                            "provider": "gemini",
                            "model_id": clean_mod,
                            "latency_ms": latency,
                            "reply": reply,
                            "detail": f"Successfully authenticated with Google Gemini ({clean_mod}).",
                        }
                    else:
                        return {
                            "status": "error",
                            "provider": "gemini",
                            "model_id": clean_mod,
                            "latency_ms": latency,
                            "reply": "",
                            "detail": f"Gemini API HTTP {resp.status_code}: {resp.text}",
                        }
            except Exception as e:
                latency = round((time.perf_counter() - t0) * 1000, 2)
                return {
                    "status": "error",
                    "provider": "gemini",
                    "model_id": mod,
                    "latency_ms": latency,
                    "reply": "",
                    "detail": f"Connection error: {e}",
                }

        # Other cloud providers via LiteLLM
        if not key:
            return {
                "status": "error",
                "provider": prov,
                "model_id": mod,
                "latency_ms": 0,
                "reply": "",
                "detail": f"API key is required for cloud provider '{prov}'.",
            }

        try:
            import litellm
            litellm.suppress_debug_info = True
            resp = await litellm.acompletion(
                model=mod,
                messages=[{"role": "user", "content": "Respond with READY"}],
                max_tokens=10,
                api_key=key,
                timeout=12.0,
            )
            latency = round((time.perf_counter() - t0) * 1000, 2)
            reply = resp.choices[0].message.content.strip()
            return {
                "status": "connected",
                "provider": prov,
                "model_id": mod,
                "latency_ms": latency,
                "reply": reply,
                "detail": f"Successfully authenticated with {prov.upper()} ({mod}).",
            }
        except Exception as e:
            latency = round((time.perf_counter() - t0) * 1000, 2)
            return {
                "status": "error",
                "provider": prov,
                "model_id": mod,
                "latency_ms": latency,
                "reply": "",
                "detail": f"Authentication failed: {e}",
            }
